// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcPvi9EWPKt-W2JYbj4ZyXDo67InJBNo',
    appId: '1:934368844631:android:a8862a16fd9c6f52c2fc12',
    messagingSenderId: '934368844631',
    projectId: 'dap-tpfinal-alonsolopezo-d5b39',
    authDomain: 'dap-tpfinal-alonsolopezo-d5b39.firebaseapp.com',
    storageBucket: 'dap-tpfinal-alonsolopezo-d5b39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkcPvi9EWPKt-W2JYbj4ZyXDo67InJBNo',
    appId: '1:934368844631:android:a8862a16fd9c6f52c2fc12',
    messagingSenderId: '934368844631',
    projectId: 'dap-tpfinal-alonsolopezo-d5b39',
    storageBucket: 'dap-tpfinal-alonsolopezo-d5b39.firebasestorage.app',
  );
}
